# Generated by Django 4.2.1 on 2023-05-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_moeda_comparacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moeda',
            old_name='valor_cota',
            new_name='alto',
        ),
        migrations.RenameField(
            model_name='moeda',
            old_name='data_cota',
            new_name='data_atualizacao',
        ),
        migrations.AddField(
            model_name='moeda',
            name='baixo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moeda',
            name='sigla',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moeda',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
