# Generated by Django 4.2.1 on 2023-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_rename_valor_cota_moeda_alto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moeda',
            name='compra',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moeda',
            name='venda',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
